return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    show_help = false,
    plugins = {
      marks = true,
      registers = true,
      spelling = {
        enabled = true,
        suggestions = 20,
      },
    },
    window = {
      border = vim.g.neo_transparent and "single" or "none",
      padding = vim.g.neo_transparent and { 0, 0, 0, 0 } or { 1, 2, 1, 2 },
    },
    icons = {
      breadcrumb = "»",
      separator = "➜",
      group = vim.g.neovide and "+ " or "🔸",
    },
    disable = {
      buftypes = { "terminal" },
      filetypes = {
        "DiffviewFiles",
        "NeogitStatus",
        "Dashboard",
        "dashboard",
        "MundoDiff",
        "NvimTree",
        "neo-tree",
        "Outline",
        "prompt",
        "Mundo",
        "alpha",
        "help",
        "dbui",
        "edgy",
        "dirbuf",
        "fugitive",
        "fugitiveblame",
        "gitcommit",
        "Trouble",
        "alpha",
        "help",
        "qf",
      },
    },
    triggers = { "<leader>", "s", "`", '"', "'", "[", "]", "z" },
    triggers_nowait = {
      "`",
      "'",
      '"',
      "g`",
      "g'",
      "<c-r>",
      "z=",
      "s",
    },
    defaults = {
      mode = { "n", "x" },
      ["g"] = { name = "Goto" },
      ["z"] = { name = "Folds" },
      ["]"] = { name = "Next" },
      ["["] = { name = "Prev" },
      ["<Leader>/"] = { name = "Telescope" },
      ["<Leader>x"] = { name = "Diagnostics" },
      ["<Leader>b"] = { name = "Buffer" },
      ["<leader>c"] = { name = "Code" },
      ["<Leader>w"] = { name = "Window" },
      ["<Leader>m"] = { name = "Miscellaneous" },
      ["<Leader>s"] = { name = "Spectre search" },
      ["<Leader>S"] = { name = "Session" },
      ["<Leader>f"] = { name = "Float" },
      ["<Leader>g"] = { name = "Git" },
      ["<Leader>u"] = { name = "Toggle options" },
      ["<Leader>t"] = { name = "Tab" },
    },
  },

  config = function(_, opts)
    require("which-key").setup(opts)
    require("which-key").register(opts.defaults)
  end,
}
